exec = quickshell kill
exec = quickshell

exec = hyprctl setcursor Breeze_Light 24

exec = hyprpaper

exec = reload_hypr_on_monitor_change

# APP BINDINGS
bind = $mainMod, RETURN, exec, $terminal -e fish -c tmux

bind = $mainMod, space, exec, $launcher

bind = $mainMod , backslash, exec, $region_ss
bind = $mainMod_SHIFT, backslash, exec, $monitor_ss
bind = $mainMod, W, exec, $browser
bind = $mainMod_Shift, W, exec, $work_browser
bind = $mainMod, N, exec, $fileManager
bind = $mainMod_SHIFT_CONTROL, L, exec, $swaylock
bind = $mainMod, c, exec, goclip
