general { 
  gaps_in = 4
  gaps_out = 6

  border_size = 1

  col.active_border = rgba(ffffffff) 
  col.inactive_border = rgba(0000000f)

  allow_tearing = true

  layout = dwindle
}

decoration {

  rounding = 5
  active_opacity = 1.0
  inactive_opacity = 1.0

  blur {
    enabled = false
      size = 8
      passes = 1
      vibrancy = 0
  }
}

animations {

  bezier = myBezier,.16,.77,.63,.96 

  animation = fade, 0
  animation = windowsOut, 0, 3, myBezier, popin
  animation = windowsIn, 1, 3, myBezier, popin
  animation = windowsMove, 1, 3, myBezier, slide
  animation = border, 1, 3, myBezier
  animation = workspaces, 1, 3, myBezier, slide
  animation = layers, 0, 3, myBezier, slide
}


misc { 
  disable_hyprland_logo = true 
    focus_on_activate = 1
}


input {

  kb_layout = us,es
  kb_options = compose:caps
  repeat_rate = 25
  repeat_delay = 200

  follow_mouse = 1
  float_switch_override_focus = 2
  mouse_refocus = 0

  sensitivity = 0.5
  accel_profile = flat,
  force_no_accel = true

  touchpad {
    natural_scroll = true
      scroll_factor = 0.5

  }
}

device {

  name = synps/2-synaptics-touchpad
  sensitivity = 0.4

}

xwayland {

  force_zero_scaling = true

}
