
workspace = 6, monitor:HDMI-A-1

monitor = eDP-1, highrr, -1920x0, 1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1
workspace = 5, monitor:eDP-1

monitor = DP-2, highrr, 0x0, 1
workspace = 1, monitor:DP-2
workspace = 6, monitor:DP-2
workspace = 8, monitor:DP-2
workspace = 9, monitor:DP-2
workspace = 10, monitor:DP-2

monitor = HDMI-A-1, highres, 1920x0, 1
workspace = 2, monitor:HDMI-A-1
workspace = 7, monitor:HDMI-A-1
