$mainMod = SUPER

$terminal = kitty

$browser = google-chrome-stable
$work_browser = chromium

$fileManager = thunar

$launcher = fuzzel 

$lockscreen = loginctl lock-session

$monitor_ss = hyprshot -z -m output
$region_ss = hyprshot -z -m region


$font = Geist

$color_transparent = 00000000

$color_black = ffffffff
$color_black_semi = ffffff08
$color_white = 080808dd
$color_error = ff0000ff
