$mainMod = SUPER

$terminal = kitty

$browser = google-chrome-stable
$work_browser = chromium

$fileManager = thunar

$menu = rofi -show drun
$launcher = rofi -show drun

$swaylock = swaylock 


$monitor_ss = hyprshot -z -m output
$region_ss = hyprshot -z -m region
