$mainMod = SUPER

$terminal = kitty

$browser = google-chrome-stable
$work_browser = chromium

$fileManager = thunar

$launcher = fuzzel 

$lockscreen = loginctl lock-session

$monitor_ss = hyprshot --mode region --raw | satty --filename - --fullscreen --input-scale 200
$region_ss = hyprshot -z -m region --clipboard-only

$OCR = hyprshot --mode region --raw | base64 -w0 > /tmp/ocr && qs ipc call ocr process && rm /tmp/ocr
$clipboard = qs ipc call clipboard open

$font = Geist

$color_transparent = 00000000

$color_black = ffffffff
$color_black_semi = ffffff08
$color_white = 080808dd
$color_error = ff0000ff
