# WORKSPACES
windowrule = workspace 1, match:class ^(kitty)$

windowrule = workspace 2, match:class ^(helium)$
windowrule = workspace 2, match:class ^(Google-chrome)$
windowrule = workspace 2, match:class ^(google-chrome)$

windowrule = workspace 3 silent, match:class ^(.*dev-linux-amd64.*)$
windowrule = workspace 3, match:class ^(thefontapp)$

windowrule = workspace 4, match:class ^(teams-for-linux)$
windowrule = workspace 4, match:class ^(com.rtosta.zapzap)$

windowrule = workspace 5, match:class ^(vesktop)$
windowrule = workspace 5, match:class ^(Spotify)$

windowrule = workspace 6, match:class ^(thunar)$
windowrule = workspace 6, match:class ^(Thunar)$

windowrule = workspace 7, match:class ^(Chromium)$
windowrule = workspace 7, match:class ^(chromium)$

windowrule = workspace 8, match:class ^(figma-linux)$

windowrule = workspace 9, match:class ^(Gimp)$
windowrule = workspace 9, match:class ^(.*libreoffice.*)$

windowrule = workspace 10, match:class ^(rdesktop)$


# FLOAT
windowrule = float on, match:class ^(Rofi)$
windowrule = float on, match:class ^(goclip)$
windowrule = float on, match:title ^(.*Picture in picture.*)$
windowrule = float on, match:title ^(.*explorer.exe.*)$
windowrule = float on, match:class ^(org.gnome.Calculator)$


# PIN
windowrule = pin on, match:title ^(.*Picture in picture.*)$
windowrule = pin on, match:title ^(.*explorer.exe.*)$


# TILE
windowrule = tile on, match:class ^(com-eviware-soapui-SoapUI)$


# NO BORDERS FOR FLOATING
windowrule = border_color rgba(00000000), match:float true
windowrule = suppress_event maximize, match:class .*

