windowrulev2 = workspace 1,class:^(kitty)$

windowrulev2 = workspace 2,class:^(helium)
windowrulev2 = workspace 2,class:^(Google-chrome)
windowrulev2 = workspace 2,class:^(google-chrome)

windowrulev2 = workspace 3 silent,class:^(.*dev-linux-amd64.*)$
windowrulev2 = workspace 3,class:^(thefontapp)$

windowrulev2 = workspace 4,class:^(teams-for-linux)$
windowrulev2 = workspace 4,class:^(com.rtosta.zapzap)$

windowrulev2 = workspace 5,class:^(vesktop)$
windowrulev2 = workspace 5,class:^(Spotify)$

windowrulev2 = workspace 6,class:^(thunar)$
windowrulev2 = workspace 6,class:^(Thunar)$

windowrulev2 = workspace 7,class:^(Chromium)$
windowrulev2 = workspace 7,class:^(chromium)$

windowrulev2 = workspace 8,class:^(figma-linux)$

windowrulev2 = workspace 9,class:^(Gimp)$
windowrulev2 = workspace 9,class:^(.*libreoffice.*)$

windowrulev2 = workspace 10,class:^(rdesktop)$


# FLOAT
windowrulev2 = float,class:^(Rofi)$
windowrulev2 = float,class:^(goclip)$
windowrulev2 = float,title:^(.*Picture in picture.*)$
windowrulev2 = float,title:^(.*explorer.exe.*)$
windowrulev2 = float,class:^(org.gnome.Calculator)$

# PIN
windowrulev2 = pin,title:^(.*Picture in picture.*)$
windowrulev2 = pin,title:^(.*explorer.exe.*)$

# TILE
windowrulev2 = tile,class:^(com-eviware-soapui-SoapUI)$


# NO BORDERS FOR FLOATING
windowrulev2 = bordercolor rgba(00000000),floating:1
windowrulev2 = suppressevent maximize, class:.*
