# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = Geist

$color_transparent = 00000000

$color_black = ffffffff
$color_black_semi = ffffff08
$color_white = 080808dd
$color_error = ff0000ff

general {
    hide_cursor = false
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true

    bezier = easeOutQuad, 0.22, 1, 0.36, 1 

    animation = fadeIn, 1, 12, easeOutQuad
    animation = fadeOut, 1, 8, easeOutQuad
    animation = inputFieldDots, 1, 0.1, easeOutQuad 
}

background {
    monitor =
    # path = ~/.files/wp/andrwui.png
    path= screenshot
    blur_passes = 2
}

input-field {

    monitor =
    size = 20%, 5%
    outline_thickness = 2
    inner_color = rgba($color_black_semi)

    outer_color = rgba($color_transparent)
    check_color = rgba($color_white)
    fail_color = rgba($color_error)

    font_color = rgba($color_black) 
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Password
    fail_text = $PAMFAIL

    dots_spacing = 0.3

    position = 0, -220
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 90
    font_family = Geist Black

    color = rgba($color_black)

    position = 0, 50
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B" # update every 60 seconds
    font_size = 25
    font_family = Geist Light

    color = rgba($color_black)

    position = 0, 150
    halign = center
    valign = center
}


# label {
#     monitor =
#     text = Welcome, $USER
#     font_size = 85
#     font_family = Geist Bold
#
#     color = rgba(080808ff)
#
#     position = 0, 0
#     halign = center
#     valign = top
# }

