$font = Geist

$color_transparent = 00000000

$color_white = ffffffff
$color_black_semi = ffffff08
$color_black = 111111ff
$color_error = ff0000ff

general = {
  background = rgba($color_black)
  base = rgba($color_black)
  accent = rgba($color_white)
}
