export const applications = await Service.import("applications")
export const audio = await Service.import("audio")
export const battery = await Service.import("battery")
export const greetd = await Service.import("greetd")
export const hyprland = await Service.import("hyprland")
export const mpris = await Service.import("mpris")
export const notifications = await Service.import("notifications")
export const systemtray = await Service.import("systemtray")