# TPM
set -g @plugin 'tmux-plugins/tpm'

#resurrect
set -g @plugin 'tmux-plugins/tmux-resurrect'

#continuum
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

# clipboard
set -g @plugin 'tmux-plugins/tmux-yank'

# auto reload config
set-option -g @plugin 'b0o/tmux-autoreload'

# appearance
set -g status-fg white
set-option -g status-style bg=default
set -g default-terminal 'tmux-256color'
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
set -g mode-style 'fg=black bg=white bold'

set -g status-position bottom
set -g status-justify center
set -g status-style 'fg=white'
set -g status-left-style 'fg=white'
set -g status-left '#S > '
set -g status-left-length 50
set -g status-right ''

set -ag message-style 'bg=white fg=#080808'
set -ag message-command-style 'fg=white bg=#080808'

set -g window-status-current-style 'fg=white bold'
set -g window-status-current-format '[#W]'

set -g window-status-format '#W'


# enabled mouse
set -g mouse on

# more confortable prefix
set -g prefix C-o

set -g n next-window


# custom session/window-manager script
bind-key C-o run-shell 'sh ~/.config/tmux/tmux-ssm.sh'
bind-key C-n run-shell 'sh ~/.config/tmux/tmux-swm.sh'

# REQUIRED AT THE BOTTOM FOR TPM
run '~/.config/tmux/plugins/tpm/tpm'


